version: '3'

services:
  webserver:
    image: nginx:1.17.9-alpine
    container_name: sm-portfolio-static
    restart: unless-stopped
    expose:
      - 80
    environment:
      VIRTUAL_HOST: sm.quesmed.com
      LETSENCRYPT_HOST: sm.quesmed.com
      LETSENCRYPT_EMAIL: smig88@gmail.com
    volumes:
      - ./html:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d

networks:
  default:
    external:
      name: nginx-proxy
