version: '3'

services:
  webserver:
    image: nginx:1.17.9-alpine
    container_name: sm-portfolio-static
    restart: unless-stopped
    expose:
      - 80
      - 443
    environment:
      - VIRTUAL_HOST=mitrasinovic.co.uk
    volumes:
      - ./html:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl

networks:
  default:
    external:
      name: nginx-proxy
