version: '3'

services:
  webserver:
    image: nginx:1.17.9-alpine
    container_name: sm-portfolio-static
    restart: unless-stopped
    expose:
      - 80
    environment:
      VIRTUAL_HOST: mitrasinovic.co.uk
      LETSENCRYPT_HOST: mitrasinovic.co.uk
      LETSENCRYPT_EMAIL: smig88@gmail.com
    volumes:
      - ./html:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - backend
      - nginx-proxy
  api:
    build: .
    container_name: sm-portfolio-api
    restart: unless-stopped
    expose:
      - 3000
    env_file: .env
    environment:
      - NODE_ENV=production
    networks:
      - backend

networks:
  backend:
    driver: bridge
  nginx-proxy:
    external: true
